### PR TITLE
add boykisser api 

### PR DESCRIPTION
**Pull request by Mkeko**
why not it should get random pic from @gizzyowo API

### CODE REVIEW

**Comment by PlOszukiwaczDEV** [comment]
nah thats crazy
m3OwOw
OwO
UwU
OwO

**Comment by PlOszukiwaczDEV** [comment]
also why tf does the bot need a fucking db?

**Comment by PlOszukiwaczDEV** [comment]
how to make 13$

**Comment by PlOszukiwaczDEV** [comment]
wait this isnt google

**Comment by GizzyUwU** [comment]
I approve of this pull request!

**Comment by PlOszukiwaczDEV** [comment]
Me too lmafo

**Comment by Mkeko** [comment]
lol 😆

**Comment by PlOszukiwaczDEV** [comment]
uwu? its merged? uwu?

**Pull request merged**
