### PR TITLE
[feat] funni embed title real

### PR DESCRIPTION
**Pull request by userandaname**
1$!@?£%£^%&^*@£%£%@^£&@£%£&&^$

### CODE REVIEW

**Comment by Cyteon** [comment]
no

**Comment by userandaname** [comment]
> no

why :(
itd be funni to have in codebase real 101% yes ok so merge plz uh yeah unclose it real yes

**Comment by userandaname** [comment]
fwegrehtrjytherwqrwgrhet

**Comment by userandaname** [comment]
:(

**Comment by userandaname** [comment]
https://open.spotify.com/track/61k7xAKMsuvTf2j2YnieSi

**Pull request closed without merging**
